networks:
  goalmine:

services:
  mvc:
    build:
      context: GoalDigger/GoalDigger.MVC
      dockerfile: ../../.docker/mvc.dockerfile
    image: abarnard1/mvc
    ports:
      - 5000:80
    networks:
      - goalmine
  api:
    build:
      context: GoalDigger/GoalDigger.API
      dockerfile: ../../.docker/api.dockerfile
    image: abarnard1/api
    ports:
      - 4000:80
    networks:
      - goalmine
    depends_on:
      - db
    environment:
      ConnectionStrings__main: "server=sql;database=GoalDiggerDB;user id=sa;password=Password12345"
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password12345"
      ACCEPT_EULA: "Y"
    networks:
      - goalmine

version: "3.7"

