networks:
  goalmine:

services:
  mvc:
    build:
      context: GoalDigger/GoalDigger.MVC
      dockerfile: ../../.docker/mvc.dockerfile
    image: 114117/mvc
    ports:
      - 5000:80
    networks:
      - goalmine
  api:
    build:
      context: GoalDigger/GoalDigger.API
      dockerfile: ../../.docker/api.dockerfile
    image: 114117/api
    ports:
      - 4000:80
    networks:
      - goalmine
    environment: 
      ConnectionStrings__<fillinlater>="server=db"
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password12345"
      ACCEPT_EULA: "Y"
    networks:
      - goalmine

version: "3.7"

